name: ru_phone_formatter
description: Mask for entering Russian phone numbers. Helps users enter their phone number comfortably
version: 1.0.1
homepage: https://github.com/Kotelnikovekb/ru_phone_formatter
repository: https://github.com/Kotelnikovekb/ru_phone_formatter

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:


